### PR TITLE
Fix MVT related issues

### PR DESCRIPTION
**Pull request by kevinzg**
Use io.BytesIO instead of StringIO when convenient. See #302, #291.
Fix EmptyResponse for PBF format.

### CODE REVIEW

**Comment by rburhum** [comment]
I am inclined on merging this. OK with you @migurski ?

**Comment by migurski** [comment]
I agree — this is important for Py3 compatibility.

**Comment by rburhum** [comment]
Ok! Done!

**Comment by duebbert** [comment]
Please release a new version to PyPI. Latest version there is from September and this merge fixed mapbox vector tiles. PyPI version doesn't work (in neither Python2 nor Python3).

**Pull request merged**
