### PR TITLE
Fix for making GridProvider python 3 ready

### PR DESCRIPTION
**Pull request by caspervdw**
First of all, thanks for your work on this great project. We use this for one of our products and encountered an issue while porting our code to python 3. Would be great to have this fix merged into master so that we don't need our fork anymore.

### CODE REVIEW

**Comment by migurski** [comment]
Thanks Casper!

**Comment by caspervdw** [comment]
I see you committed version 1.51.10 . Could you `git tag` it as well and maybe release it at pypi? So that we can pin the version in our project. Thanks in advance.

**Comment by migurski** [comment]
Certainly — that should have happened automatically, I’ll try to determine why it didn’t.

**Comment by migurski** [comment]
[The build failed](https://travis-ci.org/TileStache/TileStache/builds); I restarted it and [now 1.51.10 is on PyPI](https://pypi.org/project/TileStache/1.51.10/).

**Comment by caspervdw** [comment]
Great, thanks. Pinging @RoelvandenBerg

**Pull request merged**
